[versions]
agp = "8.13.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
retrofit = "3.0.0"
converterGson = "3.0.0"
annotations = "5.0.5"
glide = "5.0.5"
materialVersion = "1.14.0-alpha05"
eazegraph = "1.2.5l"
comGoogleGmsGoogleServicesGradlePlugin = "4.4.4"
firebaseBom = "34.5.0"
firebaseAnalytics = "23.0.0"
firebaseMessaging = "25.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
annotations = { group = "com.github.bumptech.glide", name = "annotations", version.ref = "annotations" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
google-material = { group = "com.google.android.material", name = "material", version = "1.14.0-alpha06" }
eazegraph = { group = "com.github.blackfizz", name = "eazegraph", version.ref = "eazegraph" }
com-google-gms-google-services-gradle-plugin = { group = "com.google.gms.google-services", name = "com.google.gms.google-services.gradle.plugin", version.ref = "comGoogleGmsGoogleServicesGradlePlugin" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

